// AUTO-GENERATED by scripts/resolve-roster.mjs — edit SEED there, not here.
// division and rank are curated; records and fight history are scraped live.
export const ROSTER = [
  {
    "id": "27944",
    "name": "Jon Jones",
    "div": "Heavyweight",
    "rank": "Champion"
  },
  {
    "id": "65231",
    "name": "Tom Aspinall",
    "div": "Heavyweight",
    "rank": "#1"
  },
  {
    "id": "293973",
    "name": "Ciryl Gane",
    "div": "Heavyweight",
    "rank": "#2"
  },
  {
    "id": "39537",
    "name": "Stipe Miocic",
    "div": "Heavyweight",
    "rank": "Top"
  },
  {
    "id": "170785",
    "name": "Magomed Ankalaev",
    "div": "Light Heavyweight",
    "rank": "Champion"
  },
  {
    "id": "224511",
    "name": "Alex Pereira",
    "div": "Light Heavyweight",
    "rank": "#1"
  },
  {
    "id": "97529",
    "name": "Jiri Prochazka",
    "div": "Light Heavyweight",
    "rank": "#2"
  },
  {
    "id": "146193",
    "name": "Dricus Du Plessis",
    "div": "Middleweight",
    "rank": "Champion"
  },
  {
    "id": "56374",
    "name": "Israel Adesanya",
    "div": "Middleweight",
    "rank": "Top"
  },
  {
    "id": "30452",
    "name": "Sean Strickland",
    "div": "Middleweight",
    "rank": "#2"
  },
  {
    "id": "45132",
    "name": "Robert Whittaker",
    "div": "Middleweight",
    "rank": "#3"
  },
  {
    "id": "108315",
    "name": "Belal Muhammad",
    "div": "Welterweight",
    "rank": "Champion"
  },
  {
    "id": "208155",
    "name": "Jack Della Maddalena",
    "div": "Welterweight",
    "rank": "#1"
  },
  {
    "id": "179185",
    "name": "Shavkat Rakhmonov",
    "div": "Welterweight",
    "rank": "#2"
  },
  {
    "id": "62665",
    "name": "Leon Edwards",
    "div": "Welterweight",
    "rank": "#3"
  },
  {
    "id": "76836",
    "name": "Islam Makhachev",
    "div": "Lightweight",
    "rank": "Champion"
  },
  {
    "id": "213913",
    "name": "Arman Tsarukyan",
    "div": "Lightweight",
    "rank": "#1"
  },
  {
    "id": "30300",
    "name": "Charles Oliveira",
    "div": "Lightweight",
    "rank": "#2"
  },
  {
    "id": "46648",
    "name": "Justin Gaethje",
    "div": "Lightweight",
    "rank": "#3"
  },
  {
    "id": "50529",
    "name": "Dustin Poirier",
    "div": "Lightweight",
    "rank": "Top"
  },
  {
    "id": "202445",
    "name": "Ilia Topuria",
    "div": "Featherweight",
    "rank": "Champion"
  },
  {
    "id": "101527",
    "name": "Alexander Volkanovski",
    "div": "Featherweight",
    "rank": "#1"
  },
  {
    "id": "38671",
    "name": "Max Holloway",
    "div": "Featherweight",
    "rank": "#2"
  },
  {
    "id": "157355",
    "name": "Merab Dvalishvili",
    "div": "Bantamweight",
    "rank": "Champion"
  },
  {
    "id": "135099",
    "name": "Sean O'Malley",
    "div": "Bantamweight",
    "rank": "#1"
  },
  {
    "id": "112869",
    "name": "Cory Sandhagen",
    "div": "Bantamweight",
    "rank": "#2"
  },
  {
    "id": "186873",
    "name": "Petr Yan",
    "div": "Bantamweight",
    "rank": "#3"
  },
  {
    "id": "25023",
    "name": "Alexandre Pantoja",
    "div": "Flyweight",
    "rank": "Champion"
  },
  {
    "id": "83851",
    "name": "Brandon Royval",
    "div": "Flyweight",
    "rank": "#1"
  },
  {
    "id": "80173",
    "name": "Brandon Moreno",
    "div": "Flyweight",
    "rank": "#2"
  },
  {
    "id": "29688",
    "name": "Conor McGregor",
    "div": "Lightweight",
    "rank": "Top"
  },
  {
    "id": "56035",
    "name": "Khabib Nurmagomedov",
    "div": "Lightweight",
    "rank": "Retired"
  }
];
