// One-off helper: resolves curated fighter names to Sherdog IDs and writes
// api/_lib/roster.js. Re-run with `npm run resolve-roster` after editing SEED.
import fs from 'fs';
import { searchFighter, idFromPath } from '../api/_lib/sherdog.js';

// rank: 'Champion' | '#N' | 'Top'. Edit freely — records/history are scraped live.
// Optional 4th element forces a Sherdog ID when search can't surface the fighter.
const SEED = [
  ['Jon Jones', 'Heavyweight', 'Champion', '27944'],
  ['Tom Aspinall', 'Heavyweight', '#1'],
  ['Ciryl Gane', 'Heavyweight', '#2'],
  ['Stipe Miocic', 'Heavyweight', 'Top'],
  ['Magomed Ankalaev', 'Light Heavyweight', 'Champion'],
  ['Alex Pereira', 'Light Heavyweight', '#1'],
  ['Jiri Prochazka', 'Light Heavyweight', '#2'],
  ['Dricus Du Plessis', 'Middleweight', 'Champion'],
  ['Israel Adesanya', 'Middleweight', 'Top'],
  ['Sean Strickland', 'Middleweight', '#2'],
  ['Robert Whittaker', 'Middleweight', '#3'],
  ['Belal Muhammad', 'Welterweight', 'Champion'],
  ['Jack Della Maddalena', 'Welterweight', '#1'],
  ['Shavkat Rakhmonov', 'Welterweight', '#2'],
  ['Leon Edwards', 'Welterweight', '#3'],
  ['Islam Makhachev', 'Lightweight', 'Champion'],
  ['Arman Tsarukyan', 'Lightweight', '#1'],
  ['Charles Oliveira', 'Lightweight', '#2'],
  ['Justin Gaethje', 'Lightweight', '#3'],
  ['Dustin Poirier', 'Lightweight', 'Top'],
  ['Ilia Topuria', 'Featherweight', 'Champion'],
  ['Alexander Volkanovski', 'Featherweight', '#1'],
  ['Max Holloway', 'Featherweight', '#2'],
  ['Merab Dvalishvili', 'Bantamweight', 'Champion'],
  ['Sean O\'Malley', 'Bantamweight', '#1'],
  ['Cory Sandhagen', 'Bantamweight', '#2'],
  ['Petr Yan', 'Bantamweight', '#3'],
  ['Alexandre Pantoja', 'Flyweight', 'Champion'],
  ['Brandon Royval', 'Flyweight', '#1'],
  ['Brandon Moreno', 'Flyweight', '#2'],
  ['Conor McGregor', 'Lightweight', 'Top'],
  ['Khabib Nurmagomedov', 'Lightweight', 'Retired'],
];

const out = [];
for (const [name, div, rank, forcedId] of SEED) {
  try {
    let id = forcedId;
    if (!id) {
      const path = await searchFighter(name);
      id = idFromPath(path);
      await new Promise(r => setTimeout(r, 400)); // be gentle on Sherdog
    }
    if (!id) { console.error('NOT FOUND:', name); continue; }
    console.log(`${name.padEnd(26)} -> ${id}${forcedId ? ' (forced)' : ''}`);
    out.push({ id, name, div, rank });
  } catch (e) {
    console.error('ERR', name, e.message);
  }
}

const body = `// AUTO-GENERATED by scripts/resolve-roster.mjs — edit SEED there, not here.
// division and rank are curated; records and fight history are scraped live.
export const ROSTER = ${JSON.stringify(out, null, 2)};
`;
fs.writeFileSync(new URL('../api/_lib/roster.js', import.meta.url), body);
console.log(`\nWrote ${out.length} fighters to api/_lib/roster.js`);
